# This is a basic workflow to help you get started with Actions
name: PR Validation (Learn And Share)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    #utilizing reusable workflow from provided path
    uses: ./.github/workflows/validation-workflow.yml
    #passing inputs to the reusable workflow.
    with:
      SOURCE_ORG_ALIAS: QA
      BASE_BRANCH: main
    #passing secrets to the reusable workflow.
    secrets:
      SECRET_URL_PATH: ${{secrets.DEMO_ORG_1_AUTH}}
      DOCKER_HUB_UN: ${{secrets.DOCKER_HUB_USERNAME}}
      DOCKER_HUB_PASS: ${{secrets.DOCKER_HUB_PASSWORD}}
      PROD_DOMAIN: ${{ secrets.PROD_DOMAIN }}